### ISSUE TITLE
To know where the logs are getting stored ??

### ISSUE THREAD

**Issue by Dibya19** [pingidentity/pingidentity-cdr-sandbox#55]
Hi , we would like to know where the docker logs are getting stored ?

**Comment by pdang-ping** [comment]
@Dibya19 
Generally docker logs is dependant on how the docker-daemon is configured. This is specific to your install of docker.

If you are asking about the location of the logs for the docker images - you can use the built in tools such as docker logs <container> or docker-compose logs <container> to view the standard error messages.

Otherwise the logs are stored in /opt/out/instance/logs in majority of cases.

**Comment by Dibya19** [comment]
Hi ,

The main intention in here is to clear the docker logs to avoid any space exhaustion of my aws instance. can you tell me how can we clear the logs ? any script is already been running ? or do we have to add one cron script to clear the logs , if so then i can the logs are getting stored in this path : 
/var/lib/docker/containers/<container id>/<container id>-json.log

**Comment by andrewclatham** [comment]
@Dibya19 
Adding log rotation is a great idea and we have added it to the backlog for an upcoming release. Thank you for your suggestion.

In the meantime I'd suggest 2 approaches:

1. add a cron job in each image or SSH from remote to truncate the log files in the directories previously specified by @pdang-ping 
2. Update the product configurations to enable log rotation. You can find product documentation details here: https://docs.pingidentity.com/category/readthedocs

I recommend that you watch this repo and keep an eye out for an upcoming release where we have added log rotation into the sandbox.
